<a href="https://colab.research.google.com/github/anushaGarg23/google-colab/blob/main/Numpy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Broadcasting and Vectorized Operations

In [1]:
import sys
import numpy as np

In [4]:
a = np.arange(4) # creates array from 0 to 3

In [5]:
a

array([0, 1, 2, 3])

In [6]:
a + 10 # adds 10 to all elements

array([10, 11, 12, 13])

In [7]:
a * 10

array([ 0, 10, 20, 30])

In [9]:
# The above operations did not change the original array. We are creating a new array and returning it.
a

array([0, 1, 2, 3])

In [10]:
a += 10 # This will change the original array

In [11]:
a

array([10, 11, 12, 13])

In [12]:
#Bringing Array back to normal
a -= 10

In [13]:
a

array([0, 1, 2, 3])

In [14]:
l = [0,1,2,3]

In [15]:
[i *10 for i in l]

[0, 10, 20, 30]

In [17]:
 p = np.arange(4)
 p

array([0, 1, 2, 3])

In [20]:
q = np.array([10,10,10,10])
q

array([10, 10, 10, 10])

In [21]:
p + q

array([10, 11, 12, 13])

In [22]:
p * q

array([ 0, 10, 20, 30])