<a href="https://colab.research.google.com/github/anushaGarg23/google-colab/blob/main/Numpy_Algebra_And_Size.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Algebra and size

In [2]:
import sys
import numpy as np

In [3]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [4]:
B = np.array([
    [6,5],
    [4,3],
    [2,1]
])

In [5]:
A.dot(B) # dot product

array([[20, 14],
       [56, 41],
       [92, 68]])

In [7]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [8]:
B.T # transpose of B

array([[6, 4, 2],
       [5, 3, 1]])

In [9]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

Standard Python objects take up more memory than NumPy objects; operations on NumPy objects complete very quickly compared to comparable objects in standard Python.