<a href="https://colab.research.google.com/github/anushaGarg23/google-colab/blob/main/Numpy_Boolean_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Boolean Arrays
Also called masks

In [ ]:
import sys
import numpy as np

In [ ]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [ ]:
a[0], a[-1]

(0, 3)

In [ ]:
a[[0,-1]]

array([0, 3])

In [ ]:
a[[True, True, False, True]] # True means you want to select that element and false means you don't want to

array([0, 1, 3])

In [ ]:
a[[True, False, False, False]]

array([0])

In [ ]:
a * 10

array([ 0, 10, 20, 30])

In [ ]:
a >= 2 # Tells which elements of array follow the given condition and which do not

array([False, False,  True,  True])

In [ ]:
a[a >= 2] # Filters elements of array based on the given condition

array([2, 3])

In [ ]:
a.mean()

1.5

In [ ]:
a[a > a.mean()] # Give all the elements that are greater than the mean

array([2, 3])

In [ ]:
a[~(a > a.mean())] # Give all the elements that are not greater than the mean

array([0, 1])

In [ ]:
a[(a ==0) | (a ==1)]

array([0, 1])

In [ ]:
a[(a <= 2) & (a %2 == 0)]

array([0, 2])

In [ ]:
A = np.random.randint(100, size = (3,3))

In [ ]:
A

array([[95, 55, 66],
       [96, 10, 94],
       [12, 28, 48]])

In [ ]:
A > 30

array([[ True,  True,  True],
       [ True, False,  True],
       [False, False,  True]])

In [ ]:
A[A > 30]

array([95, 55, 66, 96, 94, 48])