<a href="https://colab.research.google.com/github/anushaGarg23/google-colab/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy - Numeric Computing Library**
NumPy(Numeric Python) -> It is one of the core packages for numerical computing in Python.

In [3]:
import sys
import numpy as np

Basic Numpy Arrays

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0,-5,1,1.5,2])

# How to access individual elements of a NumPy Array?
In Numpy arrays, indexing starts from 0 i.e 0th index -> 1st element, 1st index -> 2nd element and so on

In [6]:
a[0]  # a[0] gives element of array a at 0th index i.e 1st position

1

In [7]:
a[0], a[1]

(1, 2)

Accessing elements of array in more ways

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
b[[0,2,-1]]

array([0., 1., 2.])

#Array Types

In [14]:
a

array([1, 2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b.dtype

dtype('float64')

In [19]:
c = np.array([1,2,3,4], dtype = np.float)

<ipython-input-19-9588717b1ad1>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.array([1,2,3,4], dtype = np.float)


In [20]:
c.dtype

dtype('float64')

In [21]:
d = np.array([1,2,3,4], dtype = np.int8)

In [23]:
d.dtype

dtype('int8')

In [25]:
q = np.array([{'a':1}, sys])

In [26]:
q

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

## Dimensions and shapes

In [27]:
A = np.array([
    [1,2,3],
    [4,5,6]
])

In [29]:
A.shape  # How many rows and columns are present (rows, cols)

(2, 3)

In [31]:
A.ndim   # How many dimensions

2

In [32]:
A.size #Total number of elements in the n-dim array

6

In [33]:
A[0], A[1]

(array([1, 2, 3]), array([4, 5, 6]))

In [34]:
A[-1]

array([4, 5, 6])

In [35]:
A[0:]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
A[0][0]

1

In [38]:
A[0][2]

3

In [40]:
A[0,2]

3

In [41]:
A[:,:2]

array([[1, 2],
       [4, 5]])

In [45]:
A[:2,:2]

array([[1, 2],
       [4, 5]])

In [48]:
A[:2,2:]

array([[3],
       [6]])

## Summary Statistics

In [49]:
z = np.array([1,2,3,4])

In [52]:
z.sum()

10

In [53]:
z.mean()

2.5

In [57]:
z.std() #standard deviation

1.118033988749895

In [56]:
z.var() #variance

1.25

In [58]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [59]:
x.sum()

45

In [60]:
x.mean()

5.0

In [61]:
x.std()

2.581988897471611

In [65]:
x.sum(axis = 0) # column wise sum , similar for mean and std etc

array([12, 15, 18])

In [66]:
x[0].sum()

6