<a href="https://colab.research.google.com/github/anushaGarg23/google-colab/blob/main/NumpyDemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy - Numeric Computing Library**
NumPy(Numeric Python) -> It is one of the core packages for numerical computing in Python.

In [3]:
import sys
import numpy as np

Basic Numpy Arrays

In [4]:
a = np.array([1,2,3,4])

In [5]:
b = np.array([0,-5,1,1.5,2])

# How to access individual elements of a NumPy Array?
In Numpy arrays, indexing starts from 0 i.e 0th index -> 1st element, 1st index -> 2nd element and so on

In [6]:
a[0]  # a[0] gives element of array a at 0th index i.e 1st position

1

In [7]:
a[0], a[1]

(1, 2)

Accessing elements of array in more ways

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[1:-1]

array([2, 3])

In [11]:
a[::2]

array([1, 3])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [13]:
b[[0,2,-1]]

array([0., 1., 2.])